name: Generate Docs with GitDocify

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate documentation
        uses: gitdocify/gitdocify@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
